all: int.out quad.out converge.out
	echo "Building all examples"

int.out: int.cpp
	g++ -o int.out int.cpp

quad.out: quad.cpp
	g++ -o quad.out quad.cpp

converge.out: converge.cpp
	g++ -o converge.out converge.cpp
