all: bisect.out newton.out secant.out
	echo "Building all examples"

bisect.out: bisect.cpp
	g++ -o bisect.out bisect.cpp

newton.out: newton.cpp
	g++ -o newton.out newton.cpp

secant.out: secant.cpp
	g++ -o secant.out secant.cpp
