default: random.out mc_int.out mc_converge.out pi.out dimensionality.out converge.out metropolis.out importance.out

random.out: random.cpp
	g++ random.cpp -o random.out

mc_int.out: mc_int.cpp
	g++ mc_int.cpp -o mc_int.out

mc_converge.out: mc_converge.cpp
	g++ mc_converge.cpp -o mc_converge.out

pi.out: pi.cpp
	g++ pi.cpp -o pi.out

dimensionality.out: dimensionality.cpp
	g++ dimensionality.cpp -o dimensionality.out

converge.out: converge.cpp
	g++ converge.cpp -o converge.out

metropolis.out: metropolis.cpp
	g++ metropolis.cpp -o metropolis.out

importance.out: importance.cpp
	g++ importance.cpp -o importance.out
