default: random.out mc_int.out mc_converge.out pi.out

random.out: random.cpp
	g++ random.cpp -o random.out

mc_int.out: mc_int.cpp
	g++ mc_int.cpp -o mc_int.out

mc_converge.out: mc_converge.cpp
	g++ mc_converge.cpp -o mc_converge.out

pi.out: pi.cpp
	g++ pi.cpp -o pi.out
